### ISSUE TITLE
Typo in .how

### ISSUE THREAD

**Issue by qixils** [HTSTEM/TWOW_Bot#2]
![image](https://user-images.githubusercontent.com/13265322/28999970-ddb66c68-7a29-11e7-95aa-b504db6b830b.png)  
Message says "responcively" instead of "respectively"

**Comment by hanss314** [comment]
Fixed in https://github.com/HTSTEM/TWOW_Bot/commit/69e0377aadd136f6da787daebc397f828bc02094
