### ISSUE TITLE
Setup Stable Bot

### ISSUE THREAD

**Issue by qixils** [HTSTEM/TWOW_Bot#3]
- [x] Get proper bot icon
- [x] Add mode for traditional Mini TWOWs
- [x] Merge `yaml` changes into `stable`
- [x] ~~Get someone to host it~~ ~~Decide on who's going to host~~ Actually host it
- [ ] Fix some bugs 
- [ ] Do lots of testing

**Comment by hanss314** [comment]
No one has really submitted any icons, so we're probably using the original

**Comment by qixils** [comment]
Keep art submissions open for a little bit. People need time to art:tm:

**Comment by qixils** [comment]
Added two new items to the to-do list (merge changes into `stable`, decide on who's going to host)

**Comment by qixils** [comment]
Currently waiting on some bugs to be patched... but it's coming soon:tm:

**Comment by hanss314** [comment]
I can't quite pin down what's causing #12, I'll probably just rewrite the timer system over the weekend.

**Comment by qixils** [comment]
v2 should be coming by the end of the month, along with the stable bot. you can check out the progress [here](https://github.com/HTSTEM/TWOWBot/milestone/1) (at the v2 milestone)

**Comment by hanss314** [comment]
Okay, I got stable up, but the other issues are still hanging.
