### ISSUE TITLE
Emotes in messages.

### ISSUE THREAD

**Issue by Bottersnike** [HTSTEM/TWOW_Bot#4]

**Comment by Bottersnike** [comment]
What do you mean by that when you say that hanss?

**Comment by qixils** [comment]
@Bottersnike, hanss hasn't commented on this and I'm concerned for your health

**Comment by Bottersnike** [comment]
A.) I worked out what he meant by checking in #suggestions.
B.) Why?

**Comment by qixils** [comment]
you're seemingly talking to nobody

**Comment by Bottersnike** [comment]
No one's active at the moment, and I don't have my laptop anymore, so I can't do any dev in the evenings :(

**Comment by hanss314** [comment]
Oh, it was just a suggestion by Milo to put some more emotes

**Comment by Bottersnike** [comment]
Yeah. I've thrown in some, but I'll leave this open because there are plenty that can still be added.

**Comment by qixils** [comment]
people can suggest these in new issues when they find ideas
